/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BienvenueCoachRouteImport } from './routes/bienvenue-coach'
import { Route as ConditionsGeneralesRouteImport } from './routes/conditions-generales'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as ExpressionDuJourRouteImport } from './routes/expression-du-jour'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FreeRegistrationRouteImport } from './routes/free-registration'
import { Route as HallOfFameRouteImport } from './routes/hall-of-fame'
import { Route as JeuxRouteImport } from './routes/jeux'
import { Route as Lecon01RouteImport } from './routes/lecon-01'
import { Route as Lecon02RouteImport } from './routes/lecon-02'
import { Route as LeconDemo18RouteImport } from './routes/lecon-demo-18'
import { Route as LeconsDemoRouteImport } from './routes/lecons-demo'
import { Route as MonEspaceRouteImport } from './routes/mon-espace'
import { Route as PourquoiRouteImport } from './routes/pourquoi'
import { Route as PremiereConnexionRouteImport } from './routes/premiere-connexion'
import { Route as ProgrammesRouteImport } from './routes/programmes'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TarifsRouteImport } from './routes/tarifs'
import { Route as TestNiveauRouteImport } from './routes/test-niveau'
import { Route as ZeroRouteImport } from './routes/zero'
import { Route as ExpressionDuJourJour1RouteImport } from './routes/expression-du-jour_.jour-1'
import { Route as JeuxFlashcardsRouteImport } from './routes/jeux_.flashcards'
import { Route as MonEspaceIndexRouteImport } from './routes/mon-espace/index'
import { Route as MonEspaceFamilyRouteImport } from './routes/mon-espace/family'
import { Route as MonEspaceGuideRouteImport } from './routes/mon-espace/guide'
import { Route as MonEspaceProgressRouteImport } from './routes/mon-espace/progress'
import { Route as MonEspacePulseRouteImport } from './routes/mon-espace/pulse'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BienvenueCoachRoute = BienvenueCoachRouteImport.update({
  id: '/bienvenue-coach',
  path: '/bienvenue-coach',
  getParentRoute: () => rootRouteImport,
} as any)
const ConditionsGeneralesRoute = ConditionsGeneralesRouteImport.update({
  id: '/conditions-generales',
  path: '/conditions-generales',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpressionDuJourRoute = ExpressionDuJourRouteImport.update({
  id: '/expression-du-jour',
  path: '/expression-du-jour',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FreeRegistrationRoute = FreeRegistrationRouteImport.update({
  id: '/free-registration',
  path: '/free-registration',
  getParentRoute: () => rootRouteImport,
} as any)
const HallOfFameRoute = HallOfFameRouteImport.update({
  id: '/hall-of-fame',
  path: '/hall-of-fame',
  getParentRoute: () => rootRouteImport,
} as any)
const JeuxRoute = JeuxRouteImport.update({
  id: '/jeux',
  path: '/jeux',
  getParentRoute: () => rootRouteImport,
} as any)
const Lecon01Route = Lecon01RouteImport.update({
  id: '/lecon-01',
  path: '/lecon-01',
  getParentRoute: () => rootRouteImport,
} as any)
const Lecon02Route = Lecon02RouteImport.update({
  id: '/lecon-02',
  path: '/lecon-02',
  getParentRoute: () => rootRouteImport,
} as any)
const LeconDemo18Route = LeconDemo18RouteImport.update({
  id: '/lecon-demo-18',
  path: '/lecon-demo-18',
  getParentRoute: () => rootRouteImport,
} as any)
const LeconsDemoRoute = LeconsDemoRouteImport.update({
  id: '/lecons-demo',
  path: '/lecons-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const MonEspaceRoute = MonEspaceRouteImport.update({
  id: '/mon-espace',
  path: '/mon-espace',
  getParentRoute: () => rootRouteImport,
} as any)
const PourquoiRoute = PourquoiRouteImport.update({
  id: '/pourquoi',
  path: '/pourquoi',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiereConnexionRoute = PremiereConnexionRouteImport.update({
  id: '/premiere-connexion',
  path: '/premiere-connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgrammesRoute = ProgrammesRouteImport.update({
  id: '/programmes',
  path: '/programmes',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TarifsRoute = TarifsRouteImport.update({
  id: '/tarifs',
  path: '/tarifs',
  getParentRoute: () => rootRouteImport,
} as any)
const TestNiveauRoute = TestNiveauRouteImport.update({
  id: '/test-niveau',
  path: '/test-niveau',
  getParentRoute: () => rootRouteImport,
} as any)
const ZeroRoute = ZeroRouteImport.update({
  id: '/zero',
  path: '/zero',
  getParentRoute: () => rootRouteImport,
} as any)
const ExpressionDuJourJour1Route = ExpressionDuJourJour1RouteImport.update({
  id: '/expression-du-jour_/jour-1',
  path: '/expression-du-jour/jour-1',
  getParentRoute: () => rootRouteImport,
} as any)
const JeuxFlashcardsRoute = JeuxFlashcardsRouteImport.update({
  id: '/jeux_/flashcards',
  path: '/jeux/flashcards',
  getParentRoute: () => rootRouteImport,
} as any)
const MonEspaceIndexRoute = MonEspaceIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MonEspaceRoute,
} as any)
const MonEspaceFamilyRoute = MonEspaceFamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => MonEspaceRoute,
} as any)
const MonEspaceGuideRoute = MonEspaceGuideRouteImport.update({
  id: '/guide',
  path: '/guide',
  getParentRoute: () => MonEspaceRoute,
} as any)
const MonEspaceProgressRoute = MonEspaceProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => MonEspaceRoute,
} as any)
const MonEspacePulseRoute = MonEspacePulseRouteImport.update({
  id: '/pulse',
  path: '/pulse',
  getParentRoute: () => MonEspaceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bienvenue-coach': typeof BienvenueCoachRoute
  '/conditions-generales': typeof ConditionsGeneralesRoute
  '/connexion': typeof ConnexionRoute
  '/expression-du-jour': typeof ExpressionDuJourRoute
  '/faq': typeof FaqRoute
  '/free-registration': typeof FreeRegistrationRoute
  '/hall-of-fame': typeof HallOfFameRoute
  '/jeux': typeof JeuxRoute
  '/lecon-01': typeof Lecon01Route
  '/lecon-02': typeof Lecon02Route
  '/lecon-demo-18': typeof LeconDemo18Route
  '/lecons-demo': typeof LeconsDemoRoute
  '/mon-espace': typeof MonEspaceRouteWithChildren
  '/pourquoi': typeof PourquoiRoute
  '/premiere-connexion': typeof PremiereConnexionRoute
  '/programmes': typeof ProgrammesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tarifs': typeof TarifsRoute
  '/test-niveau': typeof TestNiveauRoute
  '/zero': typeof ZeroRoute
  '/expression-du-jour/jour-1': typeof ExpressionDuJourJour1Route
  '/jeux/flashcards': typeof JeuxFlashcardsRoute
  '/mon-espace/family': typeof MonEspaceFamilyRoute
  '/mon-espace/guide': typeof MonEspaceGuideRoute
  '/mon-espace/progress': typeof MonEspaceProgressRoute
  '/mon-espace/pulse': typeof MonEspacePulseRoute
  '/mon-espace/': typeof MonEspaceIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bienvenue-coach': typeof BienvenueCoachRoute
  '/conditions-generales': typeof ConditionsGeneralesRoute
  '/connexion': typeof ConnexionRoute
  '/expression-du-jour': typeof ExpressionDuJourRoute
  '/faq': typeof FaqRoute
  '/free-registration': typeof FreeRegistrationRoute
  '/hall-of-fame': typeof HallOfFameRoute
  '/jeux': typeof JeuxRoute
  '/lecon-01': typeof Lecon01Route
  '/lecon-02': typeof Lecon02Route
  '/lecon-demo-18': typeof LeconDemo18Route
  '/lecons-demo': typeof LeconsDemoRoute
  '/pourquoi': typeof PourquoiRoute
  '/premiere-connexion': typeof PremiereConnexionRoute
  '/programmes': typeof ProgrammesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tarifs': typeof TarifsRoute
  '/test-niveau': typeof TestNiveauRoute
  '/zero': typeof ZeroRoute
  '/expression-du-jour/jour-1': typeof ExpressionDuJourJour1Route
  '/jeux/flashcards': typeof JeuxFlashcardsRoute
  '/mon-espace/family': typeof MonEspaceFamilyRoute
  '/mon-espace/guide': typeof MonEspaceGuideRoute
  '/mon-espace/progress': typeof MonEspaceProgressRoute
  '/mon-espace/pulse': typeof MonEspacePulseRoute
  '/mon-espace': typeof MonEspaceIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bienvenue-coach': typeof BienvenueCoachRoute
  '/conditions-generales': typeof ConditionsGeneralesRoute
  '/connexion': typeof ConnexionRoute
  '/expression-du-jour': typeof ExpressionDuJourRoute
  '/faq': typeof FaqRoute
  '/free-registration': typeof FreeRegistrationRoute
  '/hall-of-fame': typeof HallOfFameRoute
  '/jeux': typeof JeuxRoute
  '/lecon-01': typeof Lecon01Route
  '/lecon-02': typeof Lecon02Route
  '/lecon-demo-18': typeof LeconDemo18Route
  '/lecons-demo': typeof LeconsDemoRoute
  '/mon-espace': typeof MonEspaceRouteWithChildren
  '/pourquoi': typeof PourquoiRoute
  '/premiere-connexion': typeof PremiereConnexionRoute
  '/programmes': typeof ProgrammesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tarifs': typeof TarifsRoute
  '/test-niveau': typeof TestNiveauRoute
  '/zero': typeof ZeroRoute
  '/expression-du-jour_/jour-1': typeof ExpressionDuJourJour1Route
  '/jeux_/flashcards': typeof JeuxFlashcardsRoute
  '/mon-espace/family': typeof MonEspaceFamilyRoute
  '/mon-espace/guide': typeof MonEspaceGuideRoute
  '/mon-espace/progress': typeof MonEspaceProgressRoute
  '/mon-espace/pulse': typeof MonEspacePulseRoute
  '/mon-espace/': typeof MonEspaceIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/bienvenue-coach'
    | '/conditions-generales'
    | '/connexion'
    | '/expression-du-jour'
    | '/faq'
    | '/free-registration'
    | '/hall-of-fame'
    | '/jeux'
    | '/lecon-01'
    | '/lecon-02'
    | '/lecon-demo-18'
    | '/lecons-demo'
    | '/mon-espace'
    | '/pourquoi'
    | '/premiere-connexion'
    | '/programmes'
    | '/sitemap.xml'
    | '/tarifs'
    | '/test-niveau'
    | '/zero'
    | '/expression-du-jour/jour-1'
    | '/jeux/flashcards'
    | '/mon-espace/family'
    | '/mon-espace/guide'
    | '/mon-espace/progress'
    | '/mon-espace/pulse'
    | '/mon-espace/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/bienvenue-coach'
    | '/conditions-generales'
    | '/connexion'
    | '/expression-du-jour'
    | '/faq'
    | '/free-registration'
    | '/hall-of-fame'
    | '/jeux'
    | '/lecon-01'
    | '/lecon-02'
    | '/lecon-demo-18'
    | '/lecons-demo'
    | '/pourquoi'
    | '/premiere-connexion'
    | '/programmes'
    | '/sitemap.xml'
    | '/tarifs'
    | '/test-niveau'
    | '/zero'
    | '/expression-du-jour/jour-1'
    | '/jeux/flashcards'
    | '/mon-espace/family'
    | '/mon-espace/guide'
    | '/mon-espace/progress'
    | '/mon-espace/pulse'
    | '/mon-espace'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/bienvenue-coach'
    | '/conditions-generales'
    | '/connexion'
    | '/expression-du-jour'
    | '/faq'
    | '/free-registration'
    | '/hall-of-fame'
    | '/jeux'
    | '/lecon-01'
    | '/lecon-02'
    | '/lecon-demo-18'
    | '/lecons-demo'
    | '/mon-espace'
    | '/pourquoi'
    | '/premiere-connexion'
    | '/programmes'
    | '/sitemap.xml'
    | '/tarifs'
    | '/test-niveau'
    | '/zero'
    | '/expression-du-jour_/jour-1'
    | '/jeux_/flashcards'
    | '/mon-espace/family'
    | '/mon-espace/guide'
    | '/mon-espace/progress'
    | '/mon-espace/pulse'
    | '/mon-espace/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BienvenueCoachRoute: typeof BienvenueCoachRoute
  ConditionsGeneralesRoute: typeof ConditionsGeneralesRoute
  ConnexionRoute: typeof ConnexionRoute
  ExpressionDuJourRoute: typeof ExpressionDuJourRoute
  FaqRoute: typeof FaqRoute
  FreeRegistrationRoute: typeof FreeRegistrationRoute
  HallOfFameRoute: typeof HallOfFameRoute
  JeuxRoute: typeof JeuxRoute
  Lecon01Route: typeof Lecon01Route
  Lecon02Route: typeof Lecon02Route
  LeconDemo18Route: typeof LeconDemo18Route
  LeconsDemoRoute: typeof LeconsDemoRoute
  MonEspaceRoute: typeof MonEspaceRouteWithChildren
  PourquoiRoute: typeof PourquoiRoute
  PremiereConnexionRoute: typeof PremiereConnexionRoute
  ProgrammesRoute: typeof ProgrammesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TarifsRoute: typeof TarifsRoute
  TestNiveauRoute: typeof TestNiveauRoute
  ZeroRoute: typeof ZeroRoute
  ExpressionDuJourJour1Route: typeof ExpressionDuJourJour1Route
  JeuxFlashcardsRoute: typeof JeuxFlashcardsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bienvenue-coach': {
      id: '/bienvenue-coach'
      path: '/bienvenue-coach'
      fullPath: '/bienvenue-coach'
      preLoaderRoute: typeof BienvenueCoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conditions-generales': {
      id: '/conditions-generales'
      path: '/conditions-generales'
      fullPath: '/conditions-generales'
      preLoaderRoute: typeof ConditionsGeneralesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expression-du-jour': {
      id: '/expression-du-jour'
      path: '/expression-du-jour'
      fullPath: '/expression-du-jour'
      preLoaderRoute: typeof ExpressionDuJourRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/free-registration': {
      id: '/free-registration'
      path: '/free-registration'
      fullPath: '/free-registration'
      preLoaderRoute: typeof FreeRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hall-of-fame': {
      id: '/hall-of-fame'
      path: '/hall-of-fame'
      fullPath: '/hall-of-fame'
      preLoaderRoute: typeof HallOfFameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jeux': {
      id: '/jeux'
      path: '/jeux'
      fullPath: '/jeux'
      preLoaderRoute: typeof JeuxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecon-01': {
      id: '/lecon-01'
      path: '/lecon-01'
      fullPath: '/lecon-01'
      preLoaderRoute: typeof Lecon01RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecon-02': {
      id: '/lecon-02'
      path: '/lecon-02'
      fullPath: '/lecon-02'
      preLoaderRoute: typeof Lecon02RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecon-demo-18': {
      id: '/lecon-demo-18'
      path: '/lecon-demo-18'
      fullPath: '/lecon-demo-18'
      preLoaderRoute: typeof LeconDemo18RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lecons-demo': {
      id: '/lecons-demo'
      path: '/lecons-demo'
      fullPath: '/lecons-demo'
      preLoaderRoute: typeof LeconsDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mon-espace': {
      id: '/mon-espace'
      path: '/mon-espace'
      fullPath: '/mon-espace'
      preLoaderRoute: typeof MonEspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pourquoi': {
      id: '/pourquoi'
      path: '/pourquoi'
      fullPath: '/pourquoi'
      preLoaderRoute: typeof PourquoiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premiere-connexion': {
      id: '/premiere-connexion'
      path: '/premiere-connexion'
      fullPath: '/premiere-connexion'
      preLoaderRoute: typeof PremiereConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programmes': {
      id: '/programmes'
      path: '/programmes'
      fullPath: '/programmes'
      preLoaderRoute: typeof ProgrammesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarifs': {
      id: '/tarifs'
      path: '/tarifs'
      fullPath: '/tarifs'
      preLoaderRoute: typeof TarifsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-niveau': {
      id: '/test-niveau'
      path: '/test-niveau'
      fullPath: '/test-niveau'
      preLoaderRoute: typeof TestNiveauRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zero': {
      id: '/zero'
      path: '/zero'
      fullPath: '/zero'
      preLoaderRoute: typeof ZeroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/expression-du-jour_/jour-1': {
      id: '/expression-du-jour_/jour-1'
      path: '/expression-du-jour/jour-1'
      fullPath: '/expression-du-jour/jour-1'
      preLoaderRoute: typeof ExpressionDuJourJour1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jeux_/flashcards': {
      id: '/jeux_/flashcards'
      path: '/jeux/flashcards'
      fullPath: '/jeux/flashcards'
      preLoaderRoute: typeof JeuxFlashcardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mon-espace/': {
      id: '/mon-espace/'
      path: '/'
      fullPath: '/mon-espace/'
      preLoaderRoute: typeof MonEspaceIndexRouteImport
      parentRoute: typeof MonEspaceRoute
    }
    '/mon-espace/family': {
      id: '/mon-espace/family'
      path: '/family'
      fullPath: '/mon-espace/family'
      preLoaderRoute: typeof MonEspaceFamilyRouteImport
      parentRoute: typeof MonEspaceRoute
    }
    '/mon-espace/guide': {
      id: '/mon-espace/guide'
      path: '/guide'
      fullPath: '/mon-espace/guide'
      preLoaderRoute: typeof MonEspaceGuideRouteImport
      parentRoute: typeof MonEspaceRoute
    }
    '/mon-espace/progress': {
      id: '/mon-espace/progress'
      path: '/progress'
      fullPath: '/mon-espace/progress'
      preLoaderRoute: typeof MonEspaceProgressRouteImport
      parentRoute: typeof MonEspaceRoute
    }
    '/mon-espace/pulse': {
      id: '/mon-espace/pulse'
      path: '/pulse'
      fullPath: '/mon-espace/pulse'
      preLoaderRoute: typeof MonEspacePulseRouteImport
      parentRoute: typeof MonEspaceRoute
    }
  }
}

interface MonEspaceRouteChildren {
  MonEspaceFamilyRoute: typeof MonEspaceFamilyRoute
  MonEspaceGuideRoute: typeof MonEspaceGuideRoute
  MonEspaceProgressRoute: typeof MonEspaceProgressRoute
  MonEspacePulseRoute: typeof MonEspacePulseRoute
  MonEspaceIndexRoute: typeof MonEspaceIndexRoute
}

const MonEspaceRouteChildren: MonEspaceRouteChildren = {
  MonEspaceFamilyRoute: MonEspaceFamilyRoute,
  MonEspaceGuideRoute: MonEspaceGuideRoute,
  MonEspaceProgressRoute: MonEspaceProgressRoute,
  MonEspacePulseRoute: MonEspacePulseRoute,
  MonEspaceIndexRoute: MonEspaceIndexRoute,
}

const MonEspaceRouteWithChildren = MonEspaceRoute._addFileChildren(
  MonEspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BienvenueCoachRoute: BienvenueCoachRoute,
  ConditionsGeneralesRoute: ConditionsGeneralesRoute,
  ConnexionRoute: ConnexionRoute,
  ExpressionDuJourRoute: ExpressionDuJourRoute,
  FaqRoute: FaqRoute,
  FreeRegistrationRoute: FreeRegistrationRoute,
  HallOfFameRoute: HallOfFameRoute,
  JeuxRoute: JeuxRoute,
  Lecon01Route: Lecon01Route,
  Lecon02Route: Lecon02Route,
  LeconDemo18Route: LeconDemo18Route,
  LeconsDemoRoute: LeconsDemoRoute,
  MonEspaceRoute: MonEspaceRouteWithChildren,
  PourquoiRoute: PourquoiRoute,
  PremiereConnexionRoute: PremiereConnexionRoute,
  ProgrammesRoute: ProgrammesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TarifsRoute: TarifsRoute,
  TestNiveauRoute: TestNiveauRoute,
  ZeroRoute: ZeroRoute,
  ExpressionDuJourJour1Route: ExpressionDuJourJour1Route,
  JeuxFlashcardsRoute: JeuxFlashcardsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
